@startuml
class Jugador { 
- nombre: String
- correo: String
- contraseña: String
- deporteFavorito: Deporte
- nivelJuego: NivelJuego 
}

class Partido {
- deporte: Deporte
- duracionMin: Int
- ubicacion: Ubicacion
- horario: Timestamp
- nivelJuego: NivelJuego 
- estadoPartido: EstadoPartido
- iniciar()
- cancelar()
- cambiarEstadoPartido( algo )
}

enum Nivel {
PRINCIPIANTE
INTERMEDIO
AVANZADO
}

'class NivelJuego {
'- nivelMin: Nivel
'- nivelMax: Nivel
'- todos: Boolean 
'}

interface EstadoPartido

class Deporte {
- nombre: String
- cantidadJugadores: Int
}

class Emparejador {
- estrategia: Estrategia
}

class Reseña {}

class Estadistica {}


class Notificador {}

class ServicioCorreo {}

class Ubicacion {}
@enduml